apiVersion: v1
kind: Pod
metadata:
  name: hello-app-pod
  labels:
    app: hello-app
spec:
  containers:
  - name: hello-app-container
    image: busybox
    command: ['sh', '-c', 'echo Congrats! You deployed your first Pod to Kubernetes! && sleep 5000']
