apiVersion: apps/v1
kind: Deployment
metadata:
  name: amsterdam-deployment
  labels:
    app: amsterdam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amsterdam
  template:
    metadata:
      labels:
        app: amsterdam
    spec:
      containers:
      - name: amsterdam
        image: celinegungor/amsterdam:V2.0
        ports:
        - containerPort: 5000
